---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
- name: centos-6.8
  driver_config:
    box: bento/centos-6.8
- name: centos-7.2
  driver_config:
    box: bento/centos-7.2
- name: ubuntu-14.04
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16.04
  driver_config:
    box: bento/ubuntu-16.04

suites:
- name: default
  run_list:
    - recipe[pound]
